package org.apitests.mailbox;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import org.apitests.Token;
import org.apitests.core.Globals;
import org.apitests.core.TestRailRunner;
import org.testng.Assert;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import java.io.File;

@Listeners({TestRailRunner.class})
public class TestC138976842CreateMessage422 {

    @Test(groups = {"tp1", "mailbox"})
    public void testC138976842CreateMessage422(){

        // Generate token and set up the host
        Token token = new Token();
        RestAssured.baseURI = Globals.PROTOCOL+"://"+Globals.HOST+"/fbkmessage/api/v1/"+Globals.TENANT;
        File attachmentFile = new File("src/test/java/org/apitests/mailbox/testfiles/MessageAttachment.pdf");

        // Authentication and body set up
        RequestSpecification request = RestAssured.given();
        request.auth().oauth2(token.getTokenValue());
        request.header("Accept", "application/json");
        request.header("Content-Type", "application/json");
        request.contentType("multipart/form-data");
        request.multiPart("partnerNo", "aaa");
        request.multiPart("messageType", "NEW");
        request.multiPart("applicationNo", Globals.FUNDING_ID);
        request.multiPart("sender", "Tom Jones");
        request.multiPart("subject", "API Test");
        request.multiPart("body", "This is a message generated by an API test");
        request.multiPart("attachments", attachmentFile);

        // Response and assertion
        Response response = request.post("/message");
        Assert.assertEquals(response.statusCode(), 422, "Response code is not 422");
        Assert.assertFalse(response.jsonPath().getBoolean("_status"), "Value of the status flag is not false");
        Assert.assertEquals(response.jsonPath().getString("_messages[0].text"), "[AbxUserManagement] Failed to lookup partner / tenant with partnerId aaa", "Response text message is not correct");

    }

}
